var MAX_PLAYER_HEALTH  = 100,
	MAX_ENTITY_HEALTH  = 100,
	WORLD_DEATH_FACTOR = 0.4,
	WORLD_FIGHT_FACTOR = 0.4,
	WORLD_BIRTH_FACTOR = 1,
	MAX_BATTLE_TURNS   = 100,
	MAX_ITERATIONS	   = 1000,
	REFRESH_COUNTER    = 3,
	UNUSED_VAR;